//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reuters_Test_Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_save
    {
        public string id { get; set; }
        public string inputA { get; set; }
        public string inputB { get; set; }
        public string @operator { get; set; }
        public string data_result { get; set; }
    }
}
